Homework-31, Kubernetes 5
drsklif/microservices pull request #11
Opened 2017-12-17 16:02 UTC by drsklif

Задание выполнено в полном объеме.

1. Познакомился с пакетным менеджером Helm. Научился его устанавливать и подготавливать в специальном формате приложение со всеми зависимостями для развертывания в kubernetes.

2. В этот раз gitlab устанавливался с помощью helm. Изучил работу с окружениями и настроил необходимые пайплайны для публикации в prod и stage.

3. Не очень понял задание со звездочкой, но сделал так, чтобы при коммите в мастер-ветку выполнялалсь выкатка в prod, а при коммите во все остальные ветки, кроме мастер - выкатка в stage.

2017-12-19 13:06 UTC, chromko requested changes
1) Бинарники (.tgz) нужно заигнорить в gitignore.
2) поменять репу на свою
3) Проясни по заданию со звездочкой - что делал?
P.S. Суть задания со * была в том, чтобы при внесении любого изменения в репу приложения проходил полный пайплайн (сборка, тесты, релиз,..) вплоть до автоматическиой выкатки на production.

2017-12-19 13:06 UTC, chromko commented on kubernetes/Charts/post/values.yaml
> +  repository: chromko/post
репозиторий свой нужен

2017-12-24 11:20 UTC, drsklif commented
Исправил замечания и добавил описание выполнения задания со звездочкой

2017-12-24 11:26 UTC, drsklif commented
Хотел сделать автодеплой в staging при коммитах не в master-ветки сервисов, но не смог разобраться как триггером указать какой stage использовать.
Через триггер можно передавать переменные, но их нельзя использовать при фильтрации в пайпайне.

2017-12-25 15:15 UTC, chromko approved these changes
Теперь стало ясней.
Использование триггеров - хороший вариант. И да, есть проблема с передачей переменных (PR вроде даже есть на это).
В твоем кейсе имеет смысл мб создать ветку staging для репы с helm-чартами  и в адресе указывать `ref=staging`, тогда получишь то что нужно)
Замечаний больше нет. Все хорошо

2017-12-25 15:23 UTC, drsklif commented
Согласен, можно сделать отдельную stage-ветку для чартов, но это несколько усложняет конфигурацию деплоя. При необходимости так действительно можно сделать.
А вообще, гитлаб вроде активно развивается, может и реализуют что-то более удобное :)

2017-12-25 15:24 UTC, merged